version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - '${REACT_PORT}:${REACT_PORT}'
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '${DJANGO_PORT}:${DJANGO_PORT}'
    env_file:
      - .env
    volumes:
      - django_static:${DJANGO_STATIC_FULL_PATH}
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
    volumes:
      - django_static:${DJANGO_STATIC_FULL_PATH}
    env_file:
      - .env

  postgres:
    image: postgres:15.3
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - postgres_data:${PGDATA_PATH}
    env_file:
      - .env
    environment:
      PGDATA: ${PGDATA_PATH}

volumes:
  postgres_data:
  redis_data:
  django_static:
  django_media:
