# Generated by Django 4.2.2 on 2023-07-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('W', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
