# Generated by Django 4.2.2 on 2023-07-07 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('paused', 'Приостановлена'), ('ended', 'Закончена')], default='created', max_length=10, verbose_name='Статус')),
                ('current_player_id', models.IntegerField(blank=True, null=True, verbose_name='ID текущего игрока')),
                ('current_move_dt_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала текущего хода')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Подключен')),
                ('game_place', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Игровой номер')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
        migrations.CreateModel(
            name='GameChipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField(blank=True, null=True, verbose_name='Координата X')),
                ('y_coord', models.IntegerField(blank=True, null=True, verbose_name='Координата Y')),
                ('on_board', models.BooleanField(default=False, verbose_name='На доске')),
                ('keeper_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keep_chips', to='games.gameplayer', verbose_name='Игрок-держатель')),
                ('owner_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_chips', to='games.gameplayer', verbose_name='Игрок-родитель')),
            ],
            options={
                'verbose_name': 'фишка',
                'verbose_name_plural': 'фишки',
            },
        ),
    ]
