# Generated by Django 4.2.2 on 2023-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_room_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название комнаты'),
        ),
    ]
